"""Update table

Revision ID: 60e7e086d3a0
Revises: 5b4299009b46
Create Date: 2022-12-18 01:40:48.584448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e7e086d3a0'
down_revision = '5b4299009b46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
