"""Added table

Revision ID: 7db371729adc
Revises: 6b94255d1a22
Create Date: 2022-12-16 09:10:21.383604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db371729adc'
down_revision = '6b94255d1a22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'room_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('room_name', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
