"""Update table

Revision ID: 9ff7aa1b0cf0
Revises: cfed9e101d9a
Create Date: 2022-12-17 23:41:10.285999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff7aa1b0cf0'
down_revision = 'cfed9e101d9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('last_viewed', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'last_viewed')
    # ### end Alembic commands ###
