"""Update table

Revision ID: cfed9e101d9a
Revises: a43821315e1f
Create Date: 2022-12-17 17:40:04.948219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfed9e101d9a'
down_revision = 'a43821315e1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('massage', sa.Column('updated_dtm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('massage', 'updated_dtm')
    # ### end Alembic commands ###
